name: Automaticke Testy API

# Kdy se to má spustit? Při každém pushi na větev main!
on:
  push:
    branches: [ "main" ]

jobs:
  testovani:
    runs-on: ubuntu-latest  # GitHub nám půjčí čistý Linux

    steps:
    - name: Stáhnutí kódu z repozitáře
      uses: actions/checkout@v3

    - name: Nastavení Pythonu 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalace knihoven
      # Tady říkáme serveru, co potřebuje k běhu tvé aplikace
      run: |
         python -m pip install --upgrade pip
         pip install pytest Flask SQLAlchemy requests

        # (Kdybys v budoucnu přidal další knihovny, dopíšeš je sem)
    - name: Příprava testovací konfigurace
      run: cp config.example.py config.py

    - name: Spuštění testů
      # Tohle je ten náš kouzelný příkaz, který už znáš!
      run: |
        python -m pytest tests/test_api.py -v
